export enum ErrorCode {
    UNKNOWN,
    USER_NOT_FOUND,
    ICON_NOT_VALID,
    USER_WRONG_PASSWORD,
    LOW_BALANCE,
    USER_NOT_ALLOWED,
    ACL_GROUP_NOT_FOUND,
    LANGUAGE_CODE_DUPLICATED,
    TRANSLATION_NOT_FOUND
}
