version: '3'

services:
  prepaidlist-frontend: 
    container_name: prepaidlist-frontend
    build: 
      context: ..
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ../prepaid-list:/usr/src/app
    ports:
      - 8080:8080
    env_file:
       - .env.backend.local
