swagger: "2.0"

info:
  version: 1.0.0
  title: Prepaid List API
  description: A simple API for the drink list API

schemes:
  - http
host: localhost
basePath: /api


paths:
  /auth/login/token:
    post:
      tags:
        - auth
      summary: Login with RFID token
      description: Returns the login jwt token
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: 'body'
          name: 'body'
          required: true
          schema:
            type: object
            properties:
              token:
                type: string
      responses: 
        200:
          description: The jwt token
          schema:
            allOf:
              - $ref: '#/definitions/ApiResponse'
              - type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      type: string
        401:
          description: Failed to auth
          schema:
            allOf:
              - $ref: '#/definitions/ApiResponse'
  /auth/login/user:
    post:
      tags:
        - auth
      summary: Login the user with the username
      description: Returns the jwt token
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - username
            properties:
              username:
                type: string
      responses:
        200:
          description: The jwt token
          schema:
            allOf:
              - $ref: '#/definitions/ApiResponse'
              - type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      type: string
        401:
          description: Failed to auth
          schema:
            allOf:
              - $ref: '#/definitions/ApiResponse'
  /auth/register:
    post:
      tags:
        - auth
      summary: Register an new User
      description: Returns an new User
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            required:
              - username
            properties:
              username:
                type: string
              token:
                type: string
      responses:
        200:
          description: The jwt token
          schema:
            allOf:
              - $ref: '#/definitions/ApiResponse'
              - type: object
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      type: string
        401:
          description: Failed to register
          schema:
            allOf:
              - $ref: '#/definitions/ApiResponse'
  /user:
    get:
      tags:
        - user
      summary: The the own user profile
      description: Returns the own user object
      parameters:
        - name: Authorization
          in: header
          required: true
          type: string
      responses:
        200:
          description: The own user object
          schema:
            allOf:
              - $ref: '#/definitions/ApiResponse'
              - type: object
                required:
                  - data
                properties:
                  data:
                    allOf:
                      - $ref: '#/definitions/User'


definitions:
  User:
    type: object
    required:
      - username
    properties:
      username:
        type: string
      email:
        type: string
      name:
        type: object
        properties:
          firstname:
            type: string
          lastname:
            type: string
      balance:
        type: number

  ApiResponse:
    type: object
    required:
      - status
      - code
      - message
    properties:
      status:
        type: string
      code:
        type: integer
        minimum: 100
        maximum: 600
      message:
        type: string
      
 
 
 
 
 
 
 
 
 
