import compile from 'string-template/compile';

export const Template = {
    ERROR_USER_NOT_FOUND: compile('User {0} not found'),
    ERROR_LOW_BALANCE: compile('User {0} has low balance')
};

export enum I18n {
    INFO_SUCCESS = 'OK',
    WARN_NO_REFRESH_TOKEN = 'W_NO_REFRESH_TOKEN',
    WARN_UID_TOKEN_EXIST = 'W_UID_TOKEN_EXIST',
    WARN_UID_TOKEN_NOT_FOUND = 'W_UID_TOKEN_NOT_FOUND',
    WARN_USER_EXIST = 'W_USER_EXIST',
    WARN_USER_NOT_FOUND = 'W_USER_NOT_FOUND',
    WARN_USERS_NOT_FOUND = 'W_USERS_NOT_FOUND',
    WARN_USER_NOT_PROVIDED = 'W_USER_NOT_PROVIDED',
    WARN_USER_NOT_ALLOWED = 'W_USER_NOT_ALLOWED',
    WARN_PRODUCTS_NOT_PROVIDED = 'W_PRODUCTS_NOT_PROVIDED',
    WARN_TOTALPRICE_NOT_PROVIDED = 'W_TOTALPRICE_NOT_PROVIDED',
    WARN_NO_ORDERS_FOUND = 'W_NO_ORDERS_FOUND',
    WARN_NO_PRODUCTS_FOUND = 'W_NO_PRODUCTS_FOUND',
    WARN_NO_CATEGORIES_FOUND = 'W_NO_CATEGORIES_FOUND',
    WARN_INVALID_PARAMS = 'W_INVALID_PARAMS',
    ERR_LOW_BALANCE = 'E_LOW_BALANCE',
    ERR_ACL_GROUP_NOT_FOUND = 'E_ACL_GROUP_NOT_FOUND',
    ERR_INTERNAL_SERVER = 'E_INTERNAL_SERVER',
    ERR_LANGUAGE_CODE_DUPLICATED = 'E_LANGUAGE_CODE_DUPLICATED',
    ERR_TRANSLATION_NOT_FOUND = 'E_TRANSLATION_NOT_FOUND',
    VAL_USER_BALANCE_EXIST = 'V_BALANCE_EXIST',
    VAL_USER_ACTIVE_EXIST = 'V_USER_ACTIVE_EXIST',
    VAL_USER_ROLE_EXIST = 'V_USER_ROLE_EXIST',
    VAL_USER_USERNAME_EXIST = 'V_USER_USERNAME_EXIST',
    VAL_USER_BALANCE_NOT_PROVIDED = 'V_USER_BALANCE_NOT_PROVIDED',
    VAL_ORDER_TOTALPRICE_PROVIDED = 'V_ORDER_TOTALPRICE_PROVIDED',
    VAL_ORDER_PRODUCTS_NOT_PROVIDED = 'V_ORDER_PRODUCTS_NOT_PROVIDED',
    VAL_ORDER_USER_EXIST = 'V_ORDER_USER_EXIST',
    VAL_TRANSLATION_MISSING = 'V_TRANSLATION_MISSING',
    VAL_TRANSLATION_TYPE_MISSING = 'V_TRANSLATION_TYPE_MISSING'
}
